# Generated by Django 5.1.1 on 2024-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='Role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('formateur', 'Formateur'), ('membre', 'Membre')], default='membre', max_length=10),
        ),
    ]
