# Generated by Django 5.1.1 on 2024-09-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0002_membre_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='Role',
            new_name='role',
        ),
    ]
