# Generated by Django 5.1.1 on 2024-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0003_rename_role_membre_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
