# Generated by Django 5.1.1 on 2024-10-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0005_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='items',
            new_name='code_postal',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='zipcode',
        ),
    ]
