# Generated by Django 5.1.1 on 2024-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0006_rename_items_commande_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
