# Generated by Django 5.1.1 on 2024-10-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0007_commande_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
