# Generated by Django 5.1.1 on 2024-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0009_alter_commande_address_alter_commande_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Total',
            field=models.CharField(default='500', max_length=500),
            preserve_default=False,
        ),
    ]
