# Generated by Django 5.1.1 on 2024-10-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0010_commande_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Total',
        ),
    ]
