# Generated by Django 5.1.1 on 2024-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0012_commande_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.JSONField(),
        ),
    ]
