# Generated by Django 5.1.1 on 2024-10-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0013_alter_commande_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
