# Generated by Django 5.1.1 on 2024-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriculturalCoop', '0014_alter_commande_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url_video', models.URLField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('choix_1', models.CharField(max_length=255)),
                ('choix_2', models.CharField(max_length=255)),
                ('choix_3', models.CharField(max_length=255)),
                ('bonne_reponse', models.CharField(max_length=255)),
            ],
        ),
    ]
